MODEL:
  CHANNELS: [16,32,64,128,256]
  NUM_RES_UNITS: 3

LOSS:
  USE_LOSS: 'FastMulticlassDiceBettiMatching'         # Avilable options 'Dice', 'ClDice', 'FastMulticlassDiceBettiMatching', 'HuTopo'
  ALPHA: 0.05
  DICE_TYPE: 'dice'          # Only relevant for "FastMulticlassDiceBettiMatching"
  CLDICE_ALPHA: -1
  ALPHA_WARMUP_EPOCHS: -1
  FILTRATION: 'superlevel'
  ONE_VS_REST: False
  PUSH_UNMATCHED_TO_1_0: True
  BARCODE_LENGTH_THRESHOLD: 0.1
  IGNORE_BACKGROUND: True
  TOPOLOGY_WEIGHTS: [0.5, 0.5]

TRAIN:
  NUM_WORKERS: 16                   # Number of data loading threads
  SEED: 10                          # random seed for reproducibility
  MAX_EPOCHS: 100
  LR: 0.0008789
  BATCH_SIZE: 32                     # Batch size for a single GPU
  SAVE_PATH: "./models/"            # save path for the checkpoint
  LOG_PATH: "./runs/"               # save path for the tensorboard log
  VAL_INTERVAL: 10                   # validation interval
  LOG_INTERVAL: 1                  # wandb log interval

DATA:
  DIM: 2                                                        # data dimension
  DATA_PATH: "" # Path to dataset
  TEST_PATH: "" # Path to dataset
  DATASET: 'platelet'                                              # Dataset name
  IMG_SIZE: [200, 200]                                            # Input image size
  NUM_SAMPLES: 50                                                # Number of slices (=> this is not the number of samples because each slice is getting patched)
  IN_CHANNELS: 1
  OUT_CHANNELS: 7